#!/usr/bin/env python3
"""Generate/check ``docs/REPO_INDEX.md`` — the agent-readable file/symbol index.

A deterministic AST walk of every Python module under ``poc_v1/``,
``causal_dag_v1/``, and ``scripts/``. For each module it lists the public
top-level symbols: functions, classes, and ``UPPER_CASE`` module constants
(names not starting with ``_``).

No timestamp and no commit hash — the output is a pure function of the source,
so ``--check`` is reproducible. Freshness is the ``--check`` gate, not a stamp.

This is the committed, agent-agnostic file/symbol index: it works identically
for Claude, Codex, Gemini, and humans, with no per-agent hooks. It is the
reliable replacement for the ``/index`` skill's local-only ``PROJECT_INDEX.json``.

Usage::

    python scripts/generate_repo_index.py            # write docs/REPO_INDEX.md
    python scripts/generate_repo_index.py --check     # fail if the file is stale
"""

from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
INDEX_PATH = ROOT / "docs" / "REPO_INDEX.md"
INDEXED_DIRS = ("poc_v1", "causal_dag_v1", "scripts")
SKIP_PARTS = {"__pycache__"}


def _public_symbols(tree: ast.Module) -> list[str]:
    """Public top-level functions, classes, and UPPER_CASE constants, sorted."""
    syms: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                syms.append(f"{node.name}()")
        elif isinstance(node, ast.ClassDef):
            if not node.name.startswith("_"):
                syms.append(f"class {node.name}")
        elif isinstance(node, ast.Assign):
            for tgt in node.targets:
                if (isinstance(tgt, ast.Name)
                        and tgt.id.isupper()
                        and not tgt.id.startswith("_")):
                    syms.append(tgt.id)
    return sorted(syms)


def _modules() -> list[tuple[str, list[str]]]:
    """(relative path, public symbols) for every indexed module, sorted by path."""
    out: list[tuple[str, list[str]]] = []
    for d in INDEXED_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.py")):
            if any(part in SKIP_PARTS for part in path.parts):
                continue
            rel = path.relative_to(ROOT).as_posix()
            try:
                tree = ast.parse(path.read_text(encoding="utf-8"))
            except SyntaxError:
                out.append((rel, ["<unparseable>"]))
                continue
            out.append((rel, _public_symbols(tree)))
    return out


def build_index() -> str:
    """Return the full ``REPO_INDEX.md`` text. Deterministic — no clock, no git."""
    mods = _modules()
    lines: list[str] = []
    w = lines.append

    w("# Repository Index — market-ontology")
    w("")
    w("> **Generated by `scripts/generate_repo_index.py` — do not edit by hand.**")
    w("> Public top-level symbols per Python module under `poc_v1/`,")
    w("> `causal_dag_v1/`, and `scripts/`. Regenerate after adding or renaming a")
    w("> module or a public symbol. CI runs `generate_repo_index.py --check` and")
    w("> fails if this file is stale.")
    w("")
    w(f"{len(mods)} Python modules indexed.")
    w("")
    for rel, syms in mods:
        w(f"### `{rel}`")
        w("")
        if syms:
            for sym in syms:
                w(f"- `{sym}`")
        else:
            w("- _(no public top-level symbols)_")
        w("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or check docs/REPO_INDEX.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/REPO_INDEX.md is stale instead of writing it",
    )
    args = parser.parse_args()

    text = build_index()

    if args.check:
        if not INDEX_PATH.exists():
            print(
                f"{INDEX_PATH} is missing — run: python scripts/generate_repo_index.py",
                file=sys.stderr,
            )
            return 1
        current = INDEX_PATH.read_text()
        if current != text:
            sys.stderr.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    text.splitlines(keepends=True),
                    fromfile=str(INDEX_PATH),
                    tofile="generated",
                )
            )
            print(
                "[repo-index] STALE — run: python scripts/generate_repo_index.py",
                file=sys.stderr,
            )
            return 1
        print(f"[repo-index] OK: {INDEX_PATH}")
        return 0

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(text)
    print(f"[repo-index] wrote {INDEX_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
