#!/usr/bin/env python3
"""Generate/check ``docs/REPO_MAP.md`` — the agent-readable repository map.

The map is a *pure, deterministic projection* of the repository:

- the schema (``NODE_MODELS`` / ``EDGE_MODELS`` / ``SCHEMA_VERSION``),
- the top-level directory layout,
- the public import surface,
- the generated-artifact set.

It contains **no timestamp and no commit hash** — that would break
determinism and make ``--check`` non-reproducible. Freshness is guaranteed a
different way: CI runs ``generate_repo_map.py --check``; if the repository
changed and the map was not regenerated, CI fails. The ``--check`` gate *is*
the freshness guarantee, which is stronger than a stamp nobody re-reads.

Usage::

    python scripts/generate_repo_map.py            # write docs/REPO_MAP.md
    python scripts/generate_repo_map.py --check    # fail if the file is stale
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from poc_v1.ontology import schema  # noqa: E402

MAP_PATH = ROOT / "docs" / "REPO_MAP.md"

# Top-level directories an agent should know, with their role. Directories not
# listed still appear (role "—") so the map can never silently omit a new one.
DIR_ROLES = {
    "poc_v1": "Ontology package — schema, public modules, contracts, kg_seed fixtures.",
    "causal_dag_v1": "Causal peer module — causal hypotheses (CAUSES/MEDIATES), NetworkX acyclicity.",
    "scripts": "Generators, validators, and the scripts/agent/ harness.",
    "tests": "Unit and contract tests (python -m unittest discover -s tests).",
    "docs": "Architecture diagrams, ADRs, and this generated map.",
}

# The public import surface — what every downstream consumer imports.
PUBLIC_MODULES = [
    ("poc_v1.ontology.schema",
     "NODE_MODELS, EDGE_MODELS, SCHEMA_VERSION — the single source of truth."),
    ("poc_v1.ontology.graphiti_views",
     "ENTITY_TYPES, EDGE_TYPES, EDGE_TYPE_MAP — derived graphiti-compatible view."),
    ("poc_v1.ontology.identity",
     "CompanyIdentity, to_identity, normalize_slug — email/domain/URL → slug."),
    ("poc_v1.ontology.iri",
     "to_iri, class_iri, predicate_iri, property_iri — canonical RDF IRIs."),
]

SKIP_DIRS = {".git", ".venv", "venv", "build", "__pycache__",
             ".pytest_cache", ".ruff_cache", ".github"}


def _top_level_dirs() -> list[str]:
    return sorted(
        p.name
        for p in ROOT.iterdir()
        if p.is_dir() and p.name not in SKIP_DIRS and not p.name.endswith(".egg-info")
    )


def _generated_artifacts() -> list[str]:
    ont = ROOT / "poc_v1" / "ontology"
    return sorted(p.name for p in ont.glob("*.json")) + \
        sorted(p.name for p in ont.glob("*.ttl"))


def build_map() -> str:
    """Return the full ``REPO_MAP.md`` text. Deterministic — no clock, no git."""
    nodes = sorted(schema.NODE_MODELS)
    edges = sorted(schema.EDGE_MODELS)
    lines: list[str] = []
    w = lines.append

    w("# Repository Map — market-ontology")
    w("")
    w("> **Generated by `scripts/generate_repo_map.py` — do not edit by hand.**")
    w("> Regenerate after any schema or structure change. CI runs")
    w("> `generate_repo_map.py --check` and fails if this file is stale.")
    w("> The map is a deterministic projection of the repo (no timestamp, no")
    w("> commit hash), so `--check` is reproducible.")
    w("")
    w("`market-ontology` is the canonical Pydantic schema for the Subconscious")
    w("knowledge graph. `poc_v1/ontology/schema.py` is the single source of truth")
    w("for graph shape; everything below is derived from it.")
    w("")
    w("## Schema")
    w("")
    w(f"- **SCHEMA_VERSION:** `{schema.SCHEMA_VERSION}`")
    w(f"- **Node models ({len(nodes)}):** " + ", ".join(f"`{n}`" for n in nodes))
    w(f"- **Edge models ({len(edges)}):** " + ", ".join(f"`{e}`" for e in edges))
    w("")
    w("## Public import surface")
    w("")
    w("Every downstream consumer (spice-harvester, ai-chatbot-native-sizzle,")
    w("twenty CRM, burn-substrate) imports these modules directly:")
    w("")
    for mod, desc in PUBLIC_MODULES:
        w(f"- `{mod}` — {desc}")
    w("")
    w("## Top-level layout")
    w("")
    for d in _top_level_dirs():
        w(f"- `{d}/` — {DIR_ROLES.get(d, '—')}")
    w("")
    w("## Generated artifacts")
    w("")
    w("Under `poc_v1/ontology/` — regenerated from the schema, never hand-edited:")
    w("")
    for art in _generated_artifacts():
        w(f"- `{art}`")
    w("")
    w("## Entry points")
    w("")
    w("- Install: `pip install -e \".[dev]\"`")
    w("- Fast gate (run before any PR): `bash scripts/agent/validate-fast.sh`")
    w("- Regenerate this map: `python scripts/generate_repo_map.py`")
    w("- Agent guidance: `CLAUDE.md` (canonical; `AGENTS.md` / `GEMINI.md` symlink to it).")
    w("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or check docs/REPO_MAP.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/REPO_MAP.md is stale instead of writing it",
    )
    args = parser.parse_args()

    text = build_map()

    if args.check:
        if not MAP_PATH.exists():
            print(
                f"{MAP_PATH} is missing — run: python scripts/generate_repo_map.py",
                file=sys.stderr,
            )
            return 1
        current = MAP_PATH.read_text()
        if current != text:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                text.splitlines(keepends=True),
                fromfile=str(MAP_PATH),
                tofile="generated",
            )
            sys.stderr.writelines(diff)
            print(
                "[repo-map] STALE — run: python scripts/generate_repo_map.py",
                file=sys.stderr,
            )
            return 1
        print(f"[repo-map] OK: {MAP_PATH}")
        return 0

    MAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    MAP_PATH.write_text(text)
    print(f"[repo-map] wrote {MAP_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
